const mongoose = require('mongoose');
const userSchema=mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        unique:true,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    phone:{
        type:Number,
        required:true
    },
    address:{
        type:String
    },
    role:{
        type:String,
        default:"user"
    },
    birthday:{
        type:Date
    },
    gender:{
        type:String,
        required:true
    },
    image:{
        type:String,
        default:'https://drive.google.com/uc?export=view&id=1aXuLbzaVEu5nJ3QUxccOBcAahhLMK_fB'
    }
},{timestamp:true})
module.exports=mongoose.model('User',userSchema)